"""Making a signed notice tamper-evident.

`secret_key` existed in the settings, was generated by render.yaml, documented
in .env.example -- and read by nothing at all. Configuration that implies
security without providing it is worse than none, because it invites everyone
who reads it to assume the protection is there.

It now signs the one artefact that carries legal consequence. Nothing here
authorises anything; it makes an alteration after the fact detectable, which is
what "this notice has no effect until signed" is worth only if the signature
means something.
"""

from __future__ import annotations

import hashlib
import hmac
from datetime import datetime

from ..config import settings


def _payload(*, reference: str, scan_digest: str, officer_id: str, signed_at: datetime, body: str) -> bytes:
    """Everything the signature covers, joined unambiguously.

    The separator matters: without one, moving a character between adjacent
    fields would produce the same bytes and the same signature.
    """
    parts = [reference, scan_digest, officer_id, signed_at.isoformat(), hashlib.sha256(body.encode()).hexdigest()]
    return "".join(parts).encode("utf-8")


def sign(*, reference: str, scan_digest: str, officer_id: str, signed_at: datetime, body: str) -> str:
    return hmac.new(
        settings.secret_key.encode("utf-8"),
        _payload(reference=reference, scan_digest=scan_digest, officer_id=officer_id, signed_at=signed_at, body=body),
        hashlib.sha256,
    ).hexdigest()


def verify(signature: str | None, **fields) -> bool:
    """Whether a stored signature still matches the record it covers."""
    if not signature:
        return False
    return hmac.compare_digest(signature, sign(**fields))
